name: openiothub_plugin
description: openiothub_plugin
version: 1.0.2+66
homepage: https://github.com/OpenIoTHub

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '>=0.19.0 <= 1.0.0'
  http: ^1.1.0
  #  app内嵌网页浏览器
  flutter_vlc_player: ^7.4.0
  webview_flutter: ^4.2.1
  #  打开url
  url_launcher: ^6.1.11
  #  数据存储
  shared_preferences: ^2.1.1
  #  颜色选择器
  flutter_colorpicker: ^1.0.3
#  fluttertoast: ^8.0.8
  file_picker: ^8.0.7
  filesystem_picker: ^4.1.0
  path_provider: ^2.0.2
  dio: ^5.1.2
  openiothub_constants: ^1.0.0
  openiothub_api: ^1.0.5+7
  openiothub_grpc_api: ^1.0.0
#  gateway_grpc_api: ^1.0.0
#  iot_manager_grpc_api: ^1.0.0

  mqtt5_client: ^4.0.2
  flutter_seekbar: ^1.0.0
  oktoast: ^3.3.2+1
#  ssh
  xterm: ^4.0.0
#  dartssh2: ^2.8.2
  dartssh2: ^2.12.0
  tdesign_flutter: ^0.1.6
  cached_network_image: ^3.4.1
  flutter_svg_provider: ^1.0.7
  fl_chart: ^0.70.2
  web_socket_channel: ^3.0.2
  flutter_breadcrumb: ^1.0.1
#  右键菜单
  contextmenu: ^3.0.0
  video_player: ^2.9.5
  flutter_inappwebview: ^6.1.5
  xml: ^6.5.0
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.3
  build_runner:
  flutter_gen_runner:
  html: ^0.15.6

flutter_gen:
  assets:
    - lib/l10n/*.arb

flutter:
  uses-material-design: true
  generate: true
  assets:
#    - assets/images/
#    - assets/images/files/
    - assets/plugins/
    - assets/plugins/casa/

#flutter_intl:
#  enabled: true