name: openiothub_common_pages publish

on:
  push:
    tags: ["openiothub_common_pages-v*"]

jobs:
  publish:
    name: Publish openiothub_common_pages on pub.dev
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # This step adds the auth token for pub.dev
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Publish to pub.dev
        id: pub_release
        uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
        with:
          path: packages/openiothub_common_pages
